# Generated by Django 4.1.2 on 2023-02-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharedPacket',
            fields=[
                ('packet_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(blank=True, max_length=100000, null=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to='file/')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
