# Generated by Django 4.1.2 on 2023-02-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedpacket',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file/'),
        ),
    ]
